% Set server name plate parameters

% Copyright 2026 The MathWorks, Inc.

dataTbl = array2table([1200 350; ...
                       300 80; ...
                       1.5 1.5; ...
                       350 350; ...
                       50 50],...
           RowNames=["TDP per Die [W]",...
                     "Idle Power [W]",...
                     "Leakage increase above Nominal Temperature [W/K]",...
                     "Nominal Temperature [K]",...
                     "Thermal Capacitance [J/K]"],...
           VariableNames=["GPU","CPU"]);
