% Copyright 2026 The MathWorks, Inc.

function matFFtbl = getDesignOptionScenarioTbl(designOption,display)
    matFF = findFullFactorial({designOption.Room.Tset,...
                               designOption.Room.HVAC,...
                               designOption.Room.WinFrac,...
                               designOption.Room.OrientAng,...
                               designOption.Room.GlassTrans,...
                               designOption.Room.ThicknessWall,...
                               designOption.Room.ThicknessRoof,...
                               designOption.Room.ThicknessFloor,...
                               designOption.Room.ThicknessGlass,...
                               designOption.PDU.Tset,...
                               designOption.CoolTwr.Trange,...
                               designOption.CoolTwr.FanPowRatio,...
                               designOption.Chiller.COP,...
                               designOption.PumpEfficiency.HVAC,...
                               designOption.PumpEfficiency.CoolTwr
                               });
    matFFtbl = array2table(matFF,"VariableNames",["Room Tset",...
                                                  "Room HVAC",...
                                                  "Wall Window Fraction",...
                                                  "Room Orientation Angle",...
                                                  "Glass Transmissivity",...
                                                  "Room Wall Thickness",...
                                                  "Room Roof Thickness",...
                                                  "Room Floor Thickness",...
                                                  "Room Window Glass Thickness",...
                                                  "PDU Tset",...
                                                  "Cooling Tower T-range",...
                                                  "Cooling Tower Fan Power Ratio",...
                                                  "Chiller COP",...
                                                  "HVAC Pump Efficiency",...
                                                  "Cooling Tower Pump Efficiency"]);
    disp(strcat("Total number of design scenarios ~ ",num2str(size(matFFtbl,1))));
    disp("  ");
    if display
        disp(matFFtbl);
    end
end
