function highlightZoom(axHandle, zoomRange)
%HIGHLIGHTZOOM Draw a translucent rectangle marking a zoom region.

% Copyright 2026 The MathWorks, Inc.

yLimits = ylim(axHandle);
fill(axHandle, ...
    [zoomRange(1) zoomRange(2) zoomRange(2) zoomRange(1)], ...
    [yLimits(1) yLimits(1) yLimits(2) yLimits(2)], ...
    [0.3 0.6 0.9], 'FaceAlpha', 0.15, 'EdgeColor', [0.3 0.6 0.9], ...
    'LineStyle', '--', 'HandleVisibility', 'off');
end
