% setupMaskExpressions.m — One-time script to configure block mask parameters
% as workspace expressions. After running this, save the model.
% Blocks will evaluate expressions from the base workspace at initialization.
%
% Run once after opening the model:
%   open_system('DataCenterStability')
%   setupMaskExpressions
%   save_system('DataCenterStability')

%% UPS Block — mask parameters reference workspace variables
upsBlock = 'DataCenterStability/UPS';
set_param(upsBlock, ...
    'plantRating',              'plantRating', ...
    'baseVoltageDC',            'baseVoltageDC', ...
    'Vac',                      'Vac', ...
    'frequency',                'frequency', ...
    'capacitance',              'capacitance', ...
    'kpDC',                     'kpDC', ...
    'kiDC',                     'kiDC', ...
    'filterInductance',         'filterInductance', ...
    'filterResistance',         'filterResistance', ...
    'filterInductanceAFE',      'filterInductanceAFE', ...
    'filterResistanceAFE',      'filterResistanceAFE', ...
    'vBattMax',                 'vBattMax', ...
    'vBattNom',                 'vBattNom', ...
    'vGridMin',                 'vGridMin', ...
    'vDCThreshold',             'vDCThreshold', ...
    'initialMode',              'initialMode', ...
    'iBatt',                    'iBatt', ...
    'droopGain',                'droopGain', ...
    'rampRate',                 'rampRate', ...
    'bessConverterEfficiency',  'bessConverterEfficiency', ...
    'invKpVd',                  'invKpVd', ...
    'invKiVd',                  'invKiVd', ...
    'invKpId',                  'invKpId', ...
    'invKiId',                  'invKiId');

%% Inverter Controller — voltage/current loop gains via UPS mask pass-through
invCtrl = 'DataCenterStability/UPS/Inverter/Inverter Controller';
set_param(invCtrl, ...
    'vdPGain', 'invKpVd', ...
    'VdIGain', 'invKiVd', ...
    'IdPGain', 'invKpId', ...
    'IdIGain', 'invKiId');

%% PFC Blocks — expressions scale per-unit values by N_pfc(k)
pfcBlocks = ["DataCenterStability/PFC A", ...
             "DataCenterStability/PFC B", ...
             "DataCenterStability/PFC C"];
for k = 1:3
    set_param(pfcBlocks(k), ...
        'Kp_pfc',   sprintf('N_pfc(%d) * pfc.Kp', k), ...
        'Ki_pfc',   sprintf('N_pfc(%d) * pfc.Ki', k), ...
        'C_dc',     sprintf('N_pfc(%d) * pfc.C_dc', k), ...
        'G_damp',   sprintf('N_pfc(%d) * pfc.G_damp', k), ...
        'P_max',    sprintf('N_pfc(%d) * pfc.P_max', k), ...
        'L_ac',     sprintf('pfc.L_ac / N_pfc(%d)', k), ...
        'R_ac',     sprintf('pfc.R_ac / N_pfc(%d)', k), ...
        'V_dc_ref', 'pfc.V_dc_ref', ...
        'eta_pfc',  'pfc.eta', ...
        'tau_rms',  'pfc.tau_rms', ...
        'V_nom',    'pfc.V_nom');
end

%% Cable A — workspace variable names
set_param('DataCenterStability/Cable A', ...
    'R', 'lineResistance', ...
    'L', 'lineInductance');

%% IT Tray subsystems (DC-DC Converter + Server Tray)
itTrayBlocks = ["DataCenterStability/IT  Load A", ...
                "DataCenterStability/IT Load B", ...
                "DataCenterStability/IT Load C"];
for k = 1:3
    blk = itTrayBlocks(k);

    % DC-DC Converter
    set_param(blk + "/DC-DC Converter", ...
        'P_rated',   sprintf('itTray.dcdc.P_rated(%d)', k), ...
        'eff_rated', 'itTray.dcdc.eff * 100', ...
        'v_ref',     '1');

    % Server Tray
    set_param(blk + "/Server Tray", ...
        'nGPU',            sprintf('itTray.nGPU(%d)', k), ...
        'nCPU',            sprintf('itTray.nCPU(%d)', k), ...
        'gpuTDPperDie',    'serverTray.gpuTDPperDie', ...
        'gpuIdlePower',    'serverTray.gpuIdlePower', ...
        'gpuHBMpower',     'serverTray.gpuHBMpower', ...
        'gpuExponent',     'serverTray.gpuExponent', ...
        'gpuHBMutil',      'serverTray.gpuHBMutil', ...
        'gpuLeakage',      'serverTray.gpuLeakage', ...
        'gpuNominalDieT',  'serverTray.gpuNominalDieT', ...
        'gpuDieThermalC',  sprintf('serverTray.gpuDieThermalC_perGPU * itTray.nGPU(%d)', k), ...
        'gpuHeatSinkR',    sprintf('serverTray.gpuHeatSinkR_perGPU / itTray.nGPU(%d)', k), ...
        'gpuSurfArea',     sprintf('serverTray.gpuSurfArea_perGPU * itTray.nGPU(%d)', k), ...
        'gpuAmbientR',     sprintf('serverTray.gpuAmbientR_perGPU / itTray.nGPU(%d)', k), ...
        'trayMass',        'serverTray.trayMass', ...
        'trayCp',          'serverTray.trayCp', ...
        'trayThermalR',    sprintf('serverTray.trayThermalR_perGPU / itTray.nGPU(%d)', k), ...
        'initialT',        'serverTray.initialT', ...
        'htc',             'serverTray.htc');
end

fprintf('Mask expressions configured. Save the model with: save_system(''DataCenterStability'')\n');
