% Copyright 2026 The MathWorks, Inc.

%% Data Center for Grids
% To create a data center model library with 3-phase electrical nodes for power
% system applications, run the section of code provided below.

DatacenterModelName = "MyDatacenterModel_GRIDS";
createDataCenterWithEnclosure(NumPDUunitsX=1,NumPDUunitsY=1,...
    ModelName=DatacenterModelName,...
    ModelOption="Electrical",...
    RatingDatacenter=simscape.Value(10000,"kW"),...
    Diagnostics=true);