% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Oct-2025 14:23:32
%  MATLAB version: 25.1.0.3040723 (R2025a) Update 1
% -------------------------------------------------------------------

% Copyright 2026 The MathWorks, Inc.
                                          

Ts = 5E-5;

generator = struct;
generator.rating = 15000;%5700;
generator.frequency = 60;
generator.polePairs = 2;
generator.Vac = 480;

machine = struct;
machine.speedReference = 1;
machine.timeConstandGovernor = 0.02;
machine.timeConstantPrimeMover = 0.2;
machine.baseTorque = 79577.5 ;%18143/5;
machine.initialTorque = 53051.6*0;
machine.loadReference = 1;
machine.droop = 2;
machine.Ra = 0.03/4;
machine.Xl = 0.05/2;
machine.Xd = 1.72/2;
machine.Xq = 0.79/2;
machine.XdTransient = 0.13/2;
machine.XqTransient = 0.17/2;
machine.XdSubTransient = 0.09/2;
machine.XqSubTransient = 0.12/2;
machine.frequency = 60;
machine.tauDAxisTransient = 0.75;
machine.tauDAxisSubTransient = 0.03;
machine.tauQAxisTransient = 0.6;
machine.ratedPower = generator.rating;
machine.voltage = 480;
machine.fieldCurrent = 80;
machine.fieldVoltage = 100;
machine.polePairs = generator.polePairs;
machine.tauQAxisSubTransient = 0.02;



%% New parameters
% machine.Ra           = 0.004;    % pu
% machine.Xl           = 0.14;     % pu
% machine.Xd           = 1.20;     % pu
% machine.Xq           = 0.75;     % pu
% machine.XdTransient  = 0.25;     % pu
% machine.XqTransient  = 0.45;     % pu
% machine.XdSubTransient = 0.18;   % pu
% machine.XqSubTransient = 0.22;   % pu
% 
% machine.speedReference          = 1.0;      % pu
% machine.droop                   = 2;        % % (was 2%)
% machine.loadReference           = 0.0;      % pu (was 1.0 — critical fix)
% machine.timeConstandGovernor    = 0.08;     % s  (was 0.02s)
% machine.timeConstantPrimeMover  = 0.5;      % s  (was 0.2s)
% machine.baseTorque              = 95541;    % N·m (was 79578)
% machine.initialTorque           = 0;        % pu