function buildingBlockLayout = createBuildingLibraryAndParameterize(NameValueArgs)
% Create Simscape building using custom libraries and parameterize.
% 
% For more details, see <a href="matlab:web('FunctionReferenceList.html')">Function Reference List</a>
% 
% Copyright 2025 The MathWorks, Inc.

    arguments
        NameValueArgs.BuildingPartFile string {mustBeNonempty}
        NameValueArgs.BuildingLibraryName string {mustBeNonempty}
        NameValueArgs.ModelType string {mustBeMember(NameValueArgs.ModelType,["Heat Load Analysis","Building Energy System (TL)"])}
        NameValueArgs.Diagnostics logical {mustBeNumericOrLogical} = false
        NameValueArgs.SaveModel string {mustBeMember(NameValueArgs.SaveModel,["Create Model","Create Model and Save","Create Model and Save With Icon","Create Model, Save With Icon, and Update Path"])} = "Create Model"
        NameValueArgs.WallMaterialTable (6,5) table {mustBeNonempty}
        NameValueArgs.GroundThermalRes (1,1) simscape.Value  {simscape.mustBeCommensurateUnit(NameValueArgs.GroundThermalRes, "K/W")}
        NameValueArgs.IniBuildingTemperature (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.IniBuildingTemperature, "K")}
        NameValueArgs.HeatTransferCoeffInt (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.HeatTransferCoeffInt, "W/(K*m^2)")}
        NameValueArgs.HeatTransferCoeffExt (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.HeatTransferCoeffExt, "W/(K*m^2)")}
        NameValueArgs.PipingDataTable table {mustBeNonempty} = table(1,1)
    end
    
    dataGood = checkBuildingInputDataErrors(BuildingLibraryName=NameValueArgs.BuildingLibraryName,...
                                            ModelType=NameValueArgs.ModelType,...
                                            PipingDataTable=NameValueArgs.PipingDataTable,...
                                            SaveModel=NameValueArgs.SaveModel);
    
    % Create building if there are no input data errors.
    if dataGood
        [buildingBlockLayout,success] = createBuildingLibrary(BuildingPartFile=NameValueArgs.BuildingPartFile,...
                                                              BuildingLibraryName=NameValueArgs.BuildingLibraryName,...
                                                              ModelType=NameValueArgs.ModelType,...
                                                              Diagnostics=NameValueArgs.Diagnostics);
    else
        buildingBlockLayout = [];
        success = false;
    end
    
    if and(success,dataGood)
        % Parameterize building model.
        parameterizeBuildingLibrary(BuildingLayoutPath=buildingBlockLayout,...
                                    Diagnostics=NameValueArgs.Diagnostics,...
                                    WallMaterialTable=NameValueArgs.WallMaterialTable,...
                                    IniBuildingTemperature=NameValueArgs.IniBuildingTemperature,...
                                    GroundThermalRes=NameValueArgs.GroundThermalRes,...
                                    HeatTransferCoeffExt=NameValueArgs.HeatTransferCoeffExt,...
                                    HeatTransferCoeffInt=NameValueArgs.HeatTransferCoeffInt,...
                                    PipingDataTable=NameValueArgs.PipingDataTable);
        % Save parameterized model and add icon to it.
        if NameValueArgs.SaveModel ~= "Create Model"
            if NameValueArgs.SaveModel == "Create Model, Save With Icon, and Update Path"
                saveBuildingLibrary(ModelName=NameValueArgs.BuildingLibraryName,...
                                    ModelData=buildingBlockLayout,...
                                    AddToProjectPath=true,...
                                    AddIcon=false);
            elseif NameValueArgs.SaveModel == "Create Model and Save"
                saveBuildingLibrary(ModelName=NameValueArgs.BuildingLibraryName,...
                                    ModelData=buildingBlockLayout,...
                                    AddToProjectPath=false,...
                                    AddIcon=false);
            else
                saveBuildingLibrary(ModelName=NameValueArgs.BuildingLibraryName,...
                                    ModelData=buildingBlockLayout,...
                                    AddToProjectPath=false,...
                                    AddIcon=true);
            end
        end
    end
end