function [wallMatProp,pipingData] = initializeBuildingData(NameValueArgs)
% Initialize Simscape building data
% 
% For more details, see <a href="matlab:web('FunctionReferenceList.html')">Function Reference List</a>
% 
% Copyright 2025 The MathWorks, Inc.

    arguments
        NameValueArgs.ModelType string {mustBeMember(NameValueArgs.ModelType,["Heat Load Analysis","Building Energy System (TL)"])}
        NameValueArgs.RoofMaterial string {mustBeMember(NameValueArgs.RoofMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "Brick"
        NameValueArgs.RoofThickness simscape.Value {mustBeNonempty} = simscape.Value(0.1,"m")
        NameValueArgs.InternalWallMaterial string {mustBeMember(NameValueArgs.InternalWallMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "Wood"
        NameValueArgs.InternalWallThickness simscape.Value {mustBeNonempty} = simscape.Value(0.1,"m")
        NameValueArgs.FloorMaterial string {mustBeMember(NameValueArgs.FloorMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "Concrete"
        NameValueArgs.FloorThickness simscape.Value {mustBeNonempty} = simscape.Value(0.09,"m")
        NameValueArgs.ExternalWallMaterial string {mustBeMember(NameValueArgs.ExternalWallMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "ClinkerBrick"
        NameValueArgs.ExternalWallThickness simscape.Value {mustBeNonempty} = simscape.Value(0.08,"m")
        NameValueArgs.WindowGlassThickness simscape.Value {mustBeNonempty} = simscape.Value(0.005,"m")
        NameValueArgs.DiameterDistributor (1,1) simscape.Value  {simscape.mustBeCommensurateUnit(NameValueArgs.DiameterDistributor, "m")} = simscape.Value(0.005, "m")
        NameValueArgs.DiameterRadiator (1,1) simscape.Value  {simscape.mustBeCommensurateUnit(NameValueArgs.DiameterRadiator, "m")} = simscape.Value(0.005, "m")
        NameValueArgs.DiameterUnderFloor (1,1) simscape.Value  {simscape.mustBeCommensurateUnit(NameValueArgs.DiameterUnderFloor, "m")} = simscape.Value(0.005, "m")
        NameValueArgs.GapRadiatorPipe (1,1) simscape.Value  {simscape.mustBeCommensurateUnit(NameValueArgs.GapRadiatorPipe, "m")} = simscape.Value(0.006, "m")
        NameValueArgs.GapUnderFloorPipe (1,1) simscape.Value  {simscape.mustBeCommensurateUnit(NameValueArgs.GapUnderFloorPipe, "m")} = simscape.Value(0.006, "m")
        NameValueArgs.Diagnostics logical {mustBeNumericOrLogical} = false
    end
    
    wallMatProp = initializeBuildingCommonMaterial(...
        ExternalWallMaterial=NameValueArgs.ExternalWallMaterial,...
        ExternalWallThickness=NameValueArgs.ExternalWallThickness,...
        InternalWallMaterial=NameValueArgs.InternalWallMaterial,...
        InternalWallThickness=NameValueArgs.InternalWallThickness,...
        FloorMaterial=NameValueArgs.FloorMaterial,...
        FloorThickness=NameValueArgs.FloorThickness,...
        RoofMaterial=NameValueArgs.RoofMaterial,...
        RoofThickness=NameValueArgs.RoofThickness,...
        WindowGlassThickness=NameValueArgs.WindowGlassThickness,...
        Diagnostics=NameValueArgs.Diagnostics);
    if NameValueArgs.ModelType=="Heat Load Analysis"
        pipingData = table(1,1);
        disp(strcat("*** Piping Data not required for ",NameValueArgs.ModelType));
    else % NameValueArgs.ModelType=="Building Energy System (TL)"
        pipingData = initializeBuildingThermalParam(...
            DisplayData=NameValueArgs.Diagnostics,...
            DiameterDistributor=NameValueArgs.DiameterDistributor,...
            DiameterRadiator=NameValueArgs.DiameterRadiator,...
            DiameterUnderFloor=NameValueArgs.DiameterUnderFloor,...
            GapRadiatorPipe=NameValueArgs.GapRadiatorPipe,...
            GapUnderFloorPipe=NameValueArgs.GapUnderFloorPipe);
    end
end