function T = buildSwingTable(swingMetrics, nGPU_model, nGPU_scaled)
%BUILDSWINGTABLE Build summary table for grid power swing analysis.
%
%   T = buildSwingTable(swingMetrics) builds a table with single-SST and
%   scaled-to-100k-GPU columns from the metrics struct returned by
%   plot.gridPowerSwings.
%
%   T = buildSwingTable(swingMetrics, nGPU_model, nGPU_scaled) uses custom
%   GPU counts for the model and scaled columns (default: 4608, 100000).

% Copyright 2026 The MathWorks, Inc.

arguments
    swingMetrics struct
    nGPU_model (1,1) double = 4608
    nGPU_scaled (1,1) double = 100000
end

scaleFactor = nGPU_scaled / nGPU_model;

Metric = ["Grid Power Mean"; "Grid Power Std"; "Grid Power Peak-Peak"; ...
    "Swing (% of mean)"; "Dominant Frequency"; ...
    "Energy <1 Hz"; "Energy 1-2.5 Hz"; "Energy 7+ Hz"; ...
    "Ramp Rate (max)"; "Top 5 Frequencies"];

ModelScale = [ ...
    sprintf("%.2f MW", swingMetrics.pGrid_mean); ...
    sprintf("%.2f MW", swingMetrics.pGrid_std); ...
    sprintf("%.2f MW", swingMetrics.pGrid_pp); ...
    sprintf("%.0f%%", swingMetrics.swing_pct); ...
    sprintf("%.2f Hz", swingMetrics.dominant_freq); ...
    sprintf("%.0f%%", swingMetrics.energy_sub1Hz); ...
    sprintf("%.0f%%", swingMetrics.energy_1to2p5Hz); ...
    sprintf("%.0f%%", swingMetrics.energy_7plusHz); ...
    sprintf("%.1f MW/s", swingMetrics.max_ramp_rate); ...
    strjoin(compose("%.2f", swingMetrics.top5_freq), ", ") + " Hz"];

ScaledCol = [ ...
    sprintf("%.0f MW", swingMetrics.pGrid_mean * scaleFactor); ...
    sprintf("%.0f MW", swingMetrics.pGrid_std * scaleFactor); ...
    sprintf("%.0f MW", swingMetrics.pGrid_pp * scaleFactor); ...
    sprintf("%.0f%%", swingMetrics.swing_pct); ...
    sprintf("%.2f Hz", swingMetrics.dominant_freq); ...
    sprintf("%.0f%%", swingMetrics.energy_sub1Hz); ...
    sprintf("%.0f%%", swingMetrics.energy_1to2p5Hz); ...
    sprintf("%.0f%%", swingMetrics.energy_7plusHz); ...
    sprintf("%.0f MW/s", swingMetrics.max_ramp_rate * scaleFactor); ...
    strjoin(compose("%.2f", swingMetrics.top5_freq), ", ") + " Hz"];

modelLabel = sprintf("Single SST (%d GPUs)", nGPU_model);
scaledLabel = sprintf("Scaled to %dk GPUs", round(nGPU_scaled/1000));

T = table(Metric, ModelScale, ScaledCol, ...
    'VariableNames', ["Metric", modelLabel, scaledLabel]);
end
