function blkNameArray = addPortAndArrayOfConnection(NameValueArgs)
% Add Simscape port and Arracy Connection block, and connect them
% 
% Copyright 2025 The MathWorks, Inc.

    arguments
        NameValueArgs.Domain string {mustBeMember(NameValueArgs.Domain,["foundation.thermal.thermal","foundation.thermal_liquid.thermal_liquid"])}
        NameValueArgs.PortName string {mustBeNonempty}
        NameValueArgs.BlockPath string {mustBeNonempty}
        NameValueArgs.PortSide string {mustBeMember(NameValueArgs.PortSide,["right","left"])}
        NameValueArgs.NumberNodes (1,1) {mustBeNonnegative}
        NameValueArgs.ArrayConnectionLocation (1,4) {mustBeNonempty}
        NameValueArgs.AddLabel logical {mustBeNonempty} = false
        NameValueArgs.SizeParameters (1,3) {mustBeNonempty}
        NameValueArgs.LabelSize (1,1) {mustBeNonnegative}
    end

    if NameValueArgs.PortSide == "right"
        orient = "right";
    else
        orient = "left";
    end
    if NameValueArgs.AddLabel
        blkNameArray = addArrayConnectionBlock(BlockPath=NameValueArgs.BlockPath,...
                                               BlockName=strcat("Array",NameValueArgs.PortName),...
                                               Domain=NameValueArgs.Domain,...
                                               NumberOfNodes=NameValueArgs.NumberNodes,...
                                               BlockLocation=NameValueArgs.ArrayConnectionLocation,...
                                               AddLabel=true,...
                                               LabelName=NameValueArgs.PortName,...
                                               LabelSize=NameValueArgs.LabelSize,...
                                               Orientation=orient);
    else
        blkNameArray = addArrayConnectionBlock(BlockPath=NameValueArgs.BlockPath,...
                                               BlockName=strcat("Array",NameValueArgs.PortName),...
                                               Domain=NameValueArgs.Domain,...
                                               NumberOfNodes=NameValueArgs.NumberNodes,...
                                               BlockLocation=NameValueArgs.ArrayConnectionLocation,...
                                               AddLabel=false,...
                                               Orientation=orient);
    end
    if NameValueArgs.PortSide == "right"
        blkNameSimscapePort = addPortToCanvas(CanvasLocation=NameValueArgs.BlockPath,...
                                              PortName=NameValueArgs.PortName,...
                                              PortSide=NameValueArgs.PortSide,...
                                              PortLocation=NameValueArgs.ArrayConnectionLocation+[NameValueArgs.SizeParameters(1,1) 0 NameValueArgs.SizeParameters(1,1) -NameValueArgs.SizeParameters(1,2)*NameValueArgs.NumberNodes+NameValueArgs.SizeParameters(1,3)]);
    else
        blkNameSimscapePort = addPortToCanvas(CanvasLocation=NameValueArgs.BlockPath,...
                                              PortName=NameValueArgs.PortName,...
                                              PortSide=NameValueArgs.PortSide,...
                                              PortLocation=NameValueArgs.ArrayConnectionLocation-[NameValueArgs.SizeParameters(1,1) 0 NameValueArgs.SizeParameters(1,1) NameValueArgs.SizeParameters(1,2)*NameValueArgs.NumberNodes-NameValueArgs.SizeParameters(1,3)]);
    end
    simscape.addConnection(blkNameArray,"arrayNode",blkNameSimscapePort,"port");
end