function tbl = initializeBuildingCommonMaterial(NameValueArgs)
% Initialize common building materials.
% 
% Copyright 2025 The MathWorks, Inc.

    arguments
        NameValueArgs.RoofMaterial string {mustBeMember(NameValueArgs.RoofMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "Brick"
        NameValueArgs.RoofThickness simscape.Value {mustBeNonempty}
        NameValueArgs.InternalWallMaterial string {mustBeMember(NameValueArgs.InternalWallMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "ClinkerBrick"
        NameValueArgs.InternalWallThickness simscape.Value {mustBeNonempty}
        NameValueArgs.FloorMaterial string {mustBeMember(NameValueArgs.FloorMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "Wood"
        NameValueArgs.FloorThickness simscape.Value {mustBeNonempty}
        NameValueArgs.ExternalWallMaterial string {mustBeMember(NameValueArgs.ExternalWallMaterial,["Wood","Brick","Concrete","ClinkerBrick"])} = "Concrete"
        NameValueArgs.ExternalWallThickness simscape.Value {mustBeNonempty}
        NameValueArgs.WindowGlassThickness simscape.Value {mustBeNonempty}
        NameValueArgs.Diagnostics {mustBeNonempty} = true
    end

    matProp = load("BuildingWallMaterial.mat");
    tbl = initializeBuildingMaterialProperties(RoofDensity=matProp.Material.(NameValueArgs.RoofMaterial).Density,...
                                               RoofThermalConductivity=matProp.Material.(NameValueArgs.RoofMaterial).ThermalConductivity,...
                                               RoofHeatCapacity=matProp.Material.(NameValueArgs.RoofMaterial).HeatCapacity,...
                                               RoofThickness=NameValueArgs.RoofThickness,...
                                               ExternalWallDensity=matProp.Material.(NameValueArgs.ExternalWallMaterial).Density,...
                                               ExternalWallThermalConductivity=matProp.Material.(NameValueArgs.ExternalWallMaterial).ThermalConductivity,...
                                               ExternalWallHeatCapacity=matProp.Material.(NameValueArgs.ExternalWallMaterial).HeatCapacity,...
                                               ExternalWallThickness=NameValueArgs.ExternalWallThickness,...
                                               InternalWallDensity=matProp.Material.(NameValueArgs.InternalWallMaterial).Density,...
                                               InternalWallThermalConductivity=matProp.Material.(NameValueArgs.ExternalWallMaterial).ThermalConductivity,...
                                               InternalWallHeatCapacity=matProp.Material.(NameValueArgs.ExternalWallMaterial).HeatCapacity,...
                                               InternalWallThickness=NameValueArgs.InternalWallThickness,...
                                               FloorDensity=matProp.Material.(NameValueArgs.FloorMaterial).Density,...
                                               FloorThermalConductivity=matProp.Material.(NameValueArgs.FloorMaterial).ThermalConductivity,...
                                               FloorHeatCapacity=matProp.Material.(NameValueArgs.FloorMaterial).HeatCapacity,...
                                               FloorThickness=NameValueArgs.FloorThickness,...
                                               WindowThickness=NameValueArgs.WindowGlassThickness,...
                                               DisplayData=NameValueArgs.Diagnostics);
end