function parameterizeBuildingLibrary(NameValueArgs)
% Parameterize building library
% 
% Copyright 2025 The MathWorks, Inc.

    arguments
        NameValueArgs.BuildingLayoutPath struct {mustBeNonempty}
        NameValueArgs.Diagnostics logical {mustBeNumericOrLogical} = false
        NameValueArgs.WallMaterialTable (6,5) table {mustBeNonempty}
        NameValueArgs.GroundThermalRes (1,1) simscape.Value  {simscape.mustBeCommensurateUnit(NameValueArgs.GroundThermalRes, "K/W")}
        NameValueArgs.IniBuildingTemperature (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.IniBuildingTemperature, "K")}
        NameValueArgs.HeatTransferCoeffInt (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.HeatTransferCoeffInt, "W/(K*m^2)")}
        NameValueArgs.HeatTransferCoeffExt (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.HeatTransferCoeffExt, "W/(K*m^2)")}
        NameValueArgs.PipingDataTable table {mustBeNonempty} = table(1,1)
    end
    
    modelTL = false;
    if bdIsLoaded(NameValueArgs.BuildingLayoutPath.BuildingLibraryName)
        success = true;
        [a,b] = size(NameValueArgs.PipingDataTable);
        expectedTblFields = ["DistributorPipe","RadiatorPipe","UnderFloorPipe"];
        correctTable = all(ismember(NameValueArgs.PipingDataTable.Properties.VariableNames,expectedTblFields));
        if and(and(a==3,b==3),correctTable)
            modelTL = true;
        end
    else
        success = false;
        disp("*** ERROR ***");
        disp(strcat("    Model file ",NameValueArgs.BuildingLayoutPath.BuildingLibraryName," must be loaded."));
    end

    if success
        % Set dimensions values for building rooms and walls.
        msg = setBuildingDimensions(BuildingBlockPathData=NameValueArgs.BuildingLayoutPath.bldgBlockPath,...
                                    BuildingLibraryName=NameValueArgs.BuildingLayoutPath.BuildingLibraryName,...
                                    InternalWallThickness=simscape.Value(NameValueArgs.WallMaterialTable.InternalWall("Thickness [m]"),"m"),...
                                    ExternalWallThickness=simscape.Value(NameValueArgs.WallMaterialTable.ExternalWall("Thickness [m]"),"m"),...
                                    RoofThickness=simscape.Value(NameValueArgs.WallMaterialTable.Roof("Thickness [m]"),"m"),...
                                    FloorThickness=simscape.Value(NameValueArgs.WallMaterialTable.Floor("Thickness [m]"),"m"),...
                                    Diagnostics=NameValueArgs.Diagnostics,...
                                    DiagnosticMsgStart=NameValueArgs.BuildingLayoutPath.msg);

        % Set thermal data
        if and(NameValueArgs.BuildingLayoutPath.ModelType=="Building Energy System (TL)",modelTL)
            bldgMatTL = NameValueArgs.PipingDataTable;
        else
            bldgMatTL = table(1,1);
        end

        msg = setBuildingThermalData(BuildingBlockPathData=NameValueArgs.BuildingLayoutPath.bldgBlockPath,...
                                     BuildingLibraryName=NameValueArgs.BuildingLayoutPath.BuildingLibraryName,...
                                     DiagnosticMsgStart=msg,...
                                     Diagnostics=NameValueArgs.Diagnostics,...
                                     MaterialPropTable=NameValueArgs.WallMaterialTable,...
                                     PipingDataTable=bldgMatTL,...
                                     GroundThermalRes=NameValueArgs.GroundThermalRes,...
                                     HeatTransferCoeffExt=NameValueArgs.HeatTransferCoeffExt,...
                                     HeatTransferCoeffInt=NameValueArgs.HeatTransferCoeffInt,...
                                     IniBuildingTemperature=NameValueArgs.IniBuildingTemperature);
    
        msg = setParamForWallThermal(BuildingBlockPathData=NameValueArgs.BuildingLayoutPath.bldgBlockPath,...
                                     BuildingLibraryName=NameValueArgs.BuildingLayoutPath.BuildingLibraryName,...
                                     DiagnosticMsgStart=msg,...
                                     Diagnostics=NameValueArgs.Diagnostics,...
                                     HeatTransferCoeffExt=NameValueArgs.HeatTransferCoeffExt,...
                                     HeatTransferCoeffInt=NameValueArgs.HeatTransferCoeffInt,...
                                     MaterialPropTable=NameValueArgs.WallMaterialTable,...
                                     IniBuildingTemperature=NameValueArgs.IniBuildingTemperature,...
                                     WallName="All");

        if modelTL
            setParamForExternalPiping(BuildingBlockPathData=NameValueArgs.BuildingLayoutPath.bldgBlockPath,...
                                      BuildingLibraryName=NameValueArgs.BuildingLayoutPath.BuildingLibraryName,...
                                      DiagnosticMsgStart=msg,...
                                      Diagnostics=NameValueArgs.Diagnostics,...
                                      IniTemperature=NameValueArgs.IniBuildingTemperature,...
                                      PipingDataTable=bldgMatTL);
        end
    end
end