function data = getDataCenterNamePlateRatingTable(NameValueArgs)
    arguments
        NameValueArgs.IdlePower (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.IdlePower, "W")} = simscape.Value(25,"W")
        NameValueArgs.PowerSupplyEfficiency (1,1) {mustBeBetween(NameValueArgs.PowerSupplyEfficiency,0,100)} = 85
        NameValueArgs.ActualToNamePlateRatio (1,1) {mustBeBetween(NameValueArgs.ActualToNamePlateRatio,0,1)} = 0.6
        NameValueArgs.Mass (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.Mass, "kg")} = simscape.Value(50,"kg")
        NameValueArgs.SpecificHeat (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.SpecificHeat, "J/(kg*K)")} = simscape.Value(2500,"J/(kg*K)")
        NameValueArgs.PeakPowerCPU (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.PeakPowerCPU, "W")} = simscape.Value(40,"W")
        NameValueArgs.PeakPowerMemory (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.PeakPowerMemory, "W")} = simscape.Value(9,"W")
        NameValueArgs.PeakPowerDisk (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.PeakPowerDisk, "W")} = simscape.Value(12,"W")
        NameValueArgs.PeakPowerPCI (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.PeakPowerPCI, "W")} = simscape.Value(25,"W")
        NameValueArgs.PeakPowerMotherboard (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.PeakPowerMotherboard, "W")} = simscape.Value(25,"W")
        NameValueArgs.PeakPowerFan (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.PeakPowerFan, "W")} = simscape.Value(10,"W")
        NameValueArgs.NumberCPU (1,1) {mustBeInteger,mustBeNonnegative} = 2
        NameValueArgs.NumberMemory (1,1) {mustBeInteger,mustBeNonnegative} = 4
        NameValueArgs.NumberDisk (1,1) {mustBeInteger,mustBeNonnegative} = 1
        NameValueArgs.NumberPCI (1,1) {mustBeInteger,mustBeNonnegative} = 2
        NameValueArgs.NumberMotherboard (1,1) {mustBeInteger,mustBeNonnegative} = 1
        NameValueArgs.NumberFan (1,1) {mustBeInteger,mustBeNonnegative} = 1
        NameValueArgs.Display logical {mustBeNumericOrLogical} = false
    end
    % data = struct;
    data.powerSystemSpecs = array2table([value(NameValueArgs.IdlePower,"W");...
                                         NameValueArgs.PowerSupplyEfficiency;...
                                         NameValueArgs.ActualToNamePlateRatio;...
                                         value(NameValueArgs.Mass,"kg");...
                                         value(NameValueArgs.SpecificHeat,"J/(kg*K)")],...
                                         RowNames=["Idle Power [W]",...
                                                   "Power Supply Efficiency [%]",...
                                                   "Ratio actual to nameplate [-]",...
                                                   "Mass [kg]",...
                                                   "Specific heat [J/(kg*K)]"],...
                                         VariableNames="Value [unit]");
    data.nameplateRating = array2table([value(NameValueArgs.PeakPowerCPU,"W"),NameValueArgs.NumberCPU;...
                                        value(NameValueArgs.PeakPowerMemory,"W"),NameValueArgs.NumberMemory;...
                                        value(NameValueArgs.PeakPowerDisk,"W"),NameValueArgs.NumberDisk;...
                                        value(NameValueArgs.PeakPowerPCI,"W"),NameValueArgs.NumberPCI;...
                                        value(NameValueArgs.PeakPowerMotherboard,"W"),NameValueArgs.NumberMotherboard;...
                                        value(NameValueArgs.PeakPowerFan,"W"),NameValueArgs.NumberFan],...
                                        RowNames=["CPU",...
                                                  "Memory",...
                                                  "Disk",...
                                                  "PCI Slot",...
                                                  "Motherboard",...
                                                  "Fan"],...
                                        VariableNames=["Peak Power [W]",...
                                                       "Quantity"]);
    if NameValueArgs.Display
        disp(data.nameplateRating);
        disp(data.powerSystemSpecs);
    end
end