% Copyright 2026 The MathWorks, Inc.

modelData.StartDate = datetime(2025,1,1,1,0,0);
modelData.EndDate = datetime(2025,12,31,1,0,0);
modelData.DateTimeVec = modelData.StartDate:hours(1):modelData.EndDate;

modelData.LocationName = "London";
modelData.Location = getGeoLocationForMajorCities(CityName=modelData.LocationName);

modelData.Place.Latitude  = getGeographicalCoordinates(modelData.Location.Latitude);
modelData.Place.Longitude = getGeographicalCoordinates(modelData.Location.Longitude);
modelData.Place.Meredian  = getGeographicalCoordinates(modelData.Location.("Meredian (Time Zone)"));

modelData.YearTavg = simscape.Value([272,276; 272 278; 275 283; ... % Q1 months (min,max)
                                     278 287; 282 292; 286 295; ... % Q2 months (min,max)
                                     287 297; 284 292; 280 287; ... % Q3 months (min,max)
                                     276 281; 276 281; 272 277],... % Q4 months (min,max)
                                     "K");

[modelData.AvgDayT,modelData.AvgDayTvar,... 
 modelData.AvgNightT,modelData.AvgNightTvar] = ...
            getTemperatureFromYearlyData(... 
                              DateTimeVec=modelData.DateTimeVec,...
                              Tavg12MonthData=modelData.YearTavg,...
                              DeltaDegreesNightT=simscape.Value(10,"K"),... 
                              Plot=false,...
                              PlotName=modelData.LocationName,...
                              Location=modelData.Location,... 
                              PercentDayTimeTvar=2,...
                              PercentNightTimeTvar=3); 