% Copyright 2026 The MathWorks, Inc.

function resultTbl = getResultSummaryTbl(simResTblWeek)
    resultTbl = array2table([[round(mean(simResTblWeek.("Capacity (HVAC kW)")),2);...
                              round(mean(simResTblWeek.("Capacity (Chiller Tonnage)")),0);...
                              round(mean(simResTblWeek.("Power (W).Cooling_Tower_Fan")/1000),2);...
                              round(mean(simResTblWeek.("Power (W).Condenser_Pump")/1000),2);...
                              round(mean(simResTblWeek.PUE),2)],...
                             ["kW";"Ton";"kW";"kW";"-"]],...
                            "RowNames",["HVAC","Chiller", "Cooling Tower Fan", "Cooling Tower Pump", "PUE"],...
                            "VariableNames",["Value","Units"]);
    disp(resultTbl);
end